services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports: ["8086:8086"]
    volumes:
      - influxdb_data:/var/lib/influxdb
    #environment:
     # - DOCKER_INFLUXDB_INIT_MODE=setup
     #- DOCKER_INFLUXDB_INIT_USERNAME=admin
     # - DOCKER_INFLUXDB_INIT_PASSWORD=password
     # - DOCKER_INFLUXDB_INIT_ORG=virtual-org
     # - DOCKER_INFLUXDB_INIT_BUCKET=plant-bucket

  grafana:
    image: grafana/grafana:latest
    ports: ["3000:3000"]
    volumes:
      - grafana_data:/var/lib/grafana
  
  nodered:
    image: nodered/node-red:latest
    container_name: nodered 
    ports:
      - "1881:1880" 
    volumes:
      - ./data/node-red:/data 
    environment:
      - TZ=Europe/Stockholm 
  
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  influxdb_data:
  grafana_data:
      